// Generated by CoffeeScript 1.6.3
(function() {
  var AWS, connect, failed, fs, googleImages, handleRequest, http_get, mime, qs, request, s3, settings, url;

  http_get = require('http-get');

  googleImages = require('google-images');

  request = require('request');

  url = require('url');

  qs = require('querystring');

  fs = require('fs');

  AWS = require('aws-sdk');

  mime = require('mime');

  connect = require('connect');

  settings = require('./settings');

  failed = true;

  mime.define({
    'image/jpg': ['jpeg']
  });

  s3 = new AWS.S3({
    params: {
      Bucket: settings.amazon.bucket
    }
  });

  AWS.config.region = 'us-east-1';

  handleRequest = function(req, res) {
    var client, extension, filename, index, keyword, params, search, uri;
    uri = url.parse(req.url);
    search = uri.pathname.replace(/^\//, '').split('.');
    keyword = search[0];
    extension = search[search.length - 1];
    index = Object.keys(req.query)[0] || 0;
    filename = "" + keyword + "-" + index + "." + extension;
    params = {
      Key: filename
    };
    failed = false;
    client = googleImages(settings.google.engine_id, settings.google.api_key);
    return client.search("'" + (keyword.replace(/_/g, ' ')) + "'").then(function(results) {
      var ext, imageUrl, result;
      result = results[index || 0];
      imageUrl = result.url;
      ext = mime.extension('image/jpeg');
      filename = "" + keyword + "-" + index + "." + ext;
      return request(imageUrl).pipe(res);
    })["catch"](function(error) {
      console.log(error);
      res.writeHead(404, {
        'Content-Type': 'image/jpeg'
      });
      return fs.createReadStream('public/404.jpeg').pipe(res);
    });
  };

  connect().use(connect.favicon()).use(connect.query()).use(connect["static"]('public')).use(connect.logger('dev')).use(handleRequest).listen(3000);

}).call(this);
