// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    cache: {
      path: 'cache'
    },
    google: {
      engine_id: '018025527256606437575:vyegl_1rryy',
      api_key: 'AIzaSyAwcTf-5Nxw8Xj2bhdZ5I9XpomjOWPcnRQ'
    },
    azure: {
      api_key: 'TgZwHbcGop0SGkaT1e/ZoJfl3mPa6Bn6IBtekWWGXz0=',
      host: 'api.datamarket.azure.com',
      base_path: '/Data.ashx/Bing/Search/v1/Image',
      ssl: true
    },
    amazon: {
      bucket: 'mebe-media'
    }
  };

}).call(this);
